import { pokemonCharacters } from "./pokemon-data.generated";
import { CharacterType } from "./types";

export type Character = {
  id?: number;
  season?: number;
  rarity?: "rare";
  name: string;
  image: string;
  hint: string;
};

const rarePokemonCharacters: Character[] = [
  {
    id: 90001,
    name: "별빛냥",
    image: "/pokemon/catalog/9000101.png",
    hint: "별",
    rarity: "rare",
  },
];
export type QuizWorld = {
  slug: CharacterType;
  title: string;
  english: string;
  description: string;
  color: string;
  softColor: string;
  accent: string;
  cover: string;
  characters: Character[];
};

const mysteryAptCharacters: Character[] = [
  {
    id: 1,
    name: "벽수귀",
    image: "/mystery-apt/catalog/catalog-01.png",
    hint: "벽",
  },
  {
    id: 2,
    name: "흑진귀",
    image: "/mystery-apt/catalog/catalog-02.png",
    hint: "흑",
  },
  {
    id: 3,
    name: "팬텀토르소",
    image: "/mystery-apt/catalog/catalog-03.png",
    hint: "팬",
  },
  {
    id: 4,
    name: "헤론",
    image: "/mystery-apt/catalog/catalog-04.png",
    hint: "헤",
  },
  {
    id: 5,
    name: "마고할망",
    image: "/mystery-apt/catalog/catalog-05.png",
    hint: "마",
  },
  {
    id: 6,
    name: "객귀",
    image: "/mystery-apt/catalog/catalog-06.png",
    hint: "객",
  },
  {
    id: 7,
    name: "요하힘",
    image: "/mystery-apt/catalog/catalog-07.png",
    hint: "요",
  },
  {
    id: 8,
    name: "지하국대적",
    image: "/mystery-apt/catalog/catalog-08.png",
    hint: "지",
  },
  {
    id: 9,
    name: "네비로스",
    image: "/mystery-apt/catalog/catalog-09.png",
    hint: "네",
  },
  {
    id: 10,
    name: "마리오네트퀸",
    image: "/mystery-apt/catalog/catalog-10.png",
    hint: "마",
  },
  {
    id: 11,
    name: "치돈귀",
    image: "/mystery-apt/catalog/catalog-11.png",
    hint: "치",
  },
  {
    id: 12,
    name: "환마귀",
    image: "/mystery-apt/catalog/catalog-12.png",
    hint: "환",
  },
  {
    id: 13,
    name: "모주귀",
    image: "/mystery-apt/catalog/catalog-13.png",
    hint: "모",
  },
  {
    id: 14,
    name: "이드라",
    image: "/mystery-apt/catalog/catalog-14.png",
    hint: "이",
  },
  {
    id: 15,
    name: "무면귀",
    image: "/mystery-apt/catalog/catalog-15.png",
    hint: "무",
  },
  {
    id: 16,
    name: "그슨새",
    image: "/mystery-apt/catalog/catalog-16.png",
    hint: "그",
  },
  {
    id: 17,
    name: "불가살이",
    image: "/mystery-apt/catalog/catalog-17.png",
    hint: "불",
  },
  {
    id: 18,
    name: "인형술사",
    image: "/mystery-apt/catalog/catalog-18.png",
    hint: "인",
  },
  {
    id: 19,
    name: "호문쿨루스",
    image: "/mystery-apt/catalog/catalog-19.png",
    hint: "호",
  },
  {
    id: 20,
    name: "망부화",
    image: "/mystery-apt/catalog/catalog-20.png",
    hint: "망",
  },
  {
    id: 21,
    name: "골묘귀",
    image: "/mystery-apt/catalog/catalog-21.png",
    hint: "골",
  },
  {
    id: 22,
    name: "이안",
    image: "/mystery-apt/catalog/catalog-22.png",
    hint: "이",
  },
  {
    id: 23,
    name: "시온",
    image: "/mystery-apt/catalog/catalog-23.png",
    hint: "시",
  },
  {
    id: 24,
    name: "킬르라스",
    image: "/mystery-apt/catalog/catalog-24.png",
    hint: "키",
  },
  {
    id: 25,
    name: "라바나브",
    image: "/mystery-apt/catalog/catalog-25.png",
    hint: "라",
  },
  {
    id: 26,
    name: "림샤이코스",
    image: "/mystery-apt/catalog/catalog-26.png",
    hint: "림",
  },
  {
    id: 27,
    name: "블러드메리",
    image: "/mystery-apt/catalog/catalog-27.png",
    hint: "블",
  },
  {
    id: 28,
    name: "살음귀",
    image: "/mystery-apt/catalog/catalog-28.png",
    hint: "살",
  },
  {
    id: 29,
    name: "청목형형",
    image: "/mystery-apt/catalog/catalog-29.png",
    hint: "청",
  },
  {
    id: 30,
    name: "각귀",
    image: "/mystery-apt/catalog/catalog-30.png",
    hint: "각",
  },
  {
    id: 31,
    name: "금돼지",
    image: "/mystery-apt/catalog/catalog-31.png",
    hint: "금",
  },
  {
    id: 32,
    name: "케르베로스",
    image: "/mystery-apt/catalog/catalog-32.png",
    hint: "케",
  },
  {
    id: 33,
    name: "도한",
    image: "/mystery-apt/catalog/catalog-33.png",
    hint: "도",
  },
  {
    id: 34,
    name: "어둑시니",
    image: "/mystery-apt/catalog/catalog-34.png",
    hint: "어",
  },
  {
    id: 35,
    name: "혈안귀",
    image: "/mystery-apt/catalog/catalog-35.png",
    hint: "혈",
  },
  {
    id: 36,
    name: "블러드메리 X",
    image: "/mystery-apt/catalog/catalog-36.png",
    hint: "블",
  },
  {
    id: 37,
    name: "벨라",
    image: "/mystery-apt/catalog/catalog-37.png",
    hint: "벨",
  },
  {
    id: 38,
    name: "만티코어",
    image: "/mystery-apt/catalog/catalog-38.png",
    hint: "만",
  },
  {
    id: 39,
    name: "당목귀",
    image: "/mystery-apt/catalog/catalog-39.png",
    hint: "당",
  },
  {
    id: 40,
    name: "구미호",
    image: "/mystery-apt/catalog/catalog-40.png",
    hint: "구",
  },
  {
    id: 41,
    name: "박주민",
    image: "/mystery-apt/catalog/catalog-41.png",
    hint: "박",
  },
  {
    id: 42,
    name: "손각시",
    image: "/mystery-apt/catalog/catalog-42.png",
    hint: "손",
  },
  {
    id: 43,
    name: "진명",
    image: "/mystery-apt/catalog/catalog-43.png",
    hint: "진",
  },
  {
    id: 44,
    name: "주민누나",
    image: "/mystery-apt/catalog/catalog-44.png",
    hint: "주",
  },
  {
    id: 45,
    name: "설녀",
    image: "/mystery-apt/catalog/catalog-45.png",
    hint: "설",
  },
  {
    id: 46,
    name: "슬랜더맨",
    image: "/mystery-apt/catalog/catalog-46.png",
    hint: "슬",
  },
  {
    id: 47,
    name: "취생",
    image: "/mystery-apt/catalog/catalog-47.png",
    hint: "취",
  },
  {
    id: 48,
    name: "두억시니",
    image: "/mystery-apt/catalog/catalog-48.png",
    hint: "두",
  },
  {
    id: 49,
    name: "입질쟁이",
    image: "/mystery-apt/catalog/catalog-49.png",
    hint: "입",
  },
  {
    id: 50,
    name: "우사첩",
    image: "/mystery-apt/catalog/catalog-50.png",
    hint: "우",
  },
  {
    id: 51,
    name: "양괭이",
    image: "/mystery-apt/catalog/catalog-51.png",
    hint: "양",
  },
  {
    id: 52,
    name: "시두스",
    image: "/mystery-apt/catalog/catalog-52.png",
    hint: "시",
  },
  {
    id: 53,
    name: "인큐버스",
    image: "/mystery-apt/catalog/catalog-53.png",
    hint: "인",
  },
  {
    id: 54,
    name: "지네귀신",
    image: "/mystery-apt/catalog/catalog-54.png",
    hint: "지",
  },
];

const wishcatCharacters: Character[] = [
  { name: "아이냥", image: "/wishcat/catalog/ainyang.png", hint: "아" },
  { name: "알로하냥", image: "/wishcat/catalog/alohanyang.png", hint: "알" },
  { name: "나비냥", image: "/wishcat/catalog/nabinyang.png", hint: "나" },
  { name: "베베냥", image: "/wishcat/catalog/bebenyang.png", hint: "베" },
  { name: "라떼냥", image: "/wishcat/catalog/lattenyang.png", hint: "라" },
  { name: "이쁘냥", image: "/wishcat/catalog/ippeunyang.png", hint: "이" },
  { name: "러브냥", image: "/wishcat/catalog/loveyang.png", hint: "러" },
  {
    name: "쨍쨍냥",
    image: "/wishcat/catalog/jjaengjjaengnyang.png",
    hint: "쨍",
  },
  { name: "똑똑냥", image: "/wishcat/catalog/ttokttoknyang.png", hint: "똑" },
  { name: "헬씨냥", image: "/wishcat/catalog/healthynyang.png", hint: "헬" },
  { name: "닥터냥", image: "/wishcat/catalog/doctornyang.png", hint: "닥" },
  { name: "꾸미냥", image: "/wishcat/catalog/kkuminyang.png", hint: "꾸" },
  { name: "난다냥", image: "/wishcat/catalog/nandanyang.png", hint: "난" },
  { name: "달달냥", image: "/wishcat/catalog/daldalnyang.png", hint: "달" },
  { name: "빠삐냥", image: "/wishcat/catalog/ppappinyang.png", hint: "빠" },
  { name: "아트냥", image: "/wishcat/catalog/artnyang.png", hint: "아" },
  { name: "우아냥", image: "/wishcat/catalog/woanyang.png", hint: "우" },
  { name: "코코냥", image: "/wishcat/catalog/kokonyang.png", hint: "코" },
  { name: "샴푸냥", image: "/wishcat/catalog/shampoonyang.png", hint: "샴" },
];

const quizWorldData: QuizWorld[] = [
  {
    slug: "pokemon",
    title: "포켓몬",
    english: "POKÉMON",
    description: "1,025마리 포켓몬 친구들",
    color: "#ff705d",
    softColor: "#fff1e9",
    accent: "#ffb92e",
    cover: "https://data1.pokemonkorea.co.kr/newdata/pokedex/mid/002501.png",
    characters: [...rarePokemonCharacters, ...pokemonCharacters],
  },
  {
    slug: "teenieping",
    title: "티니핑",
    english: "TEENIEPING",
    description: "153명의 반짝이는 티니핑",
    color: "#ff77aa",
    softColor: "#fff0f7",
    accent: "#ff9dc2",
    cover: "/teenieping/catalog/season-1-03.png",
    characters: [
      {
        name: "하츄핑",
        image: "/teenieping/catalog/season-1-01.png",
        hint: "하",
        season: 1,
      },
      {
        name: "바로핑",
        image: "/teenieping/catalog/season-1-02.png",
        hint: "바",
        season: 1,
      },
      {
        name: "아자핑",
        image: "/teenieping/catalog/season-1-03.png",
        hint: "아",
        season: 1,
      },
      {
        name: "차차핑",
        image: "/teenieping/catalog/season-1-04.png",
        hint: "차",
        season: 1,
      },
      {
        name: "라라핑",
        image: "/teenieping/catalog/season-1-05.png",
        hint: "라",
        season: 1,
      },
      {
        name: "해핑",
        image: "/teenieping/catalog/season-1-06.png",
        hint: "해",
        season: 1,
      },
      {
        name: "키키핑",
        image: "/teenieping/catalog/season-1-07.png",
        hint: "키",
        season: 1,
      },
      {
        name: "아잉핑",
        image: "/teenieping/catalog/season-1-08.png",
        hint: "아",
        season: 1,
      },
      {
        name: "부끄핑",
        image: "/teenieping/catalog/season-1-09.png",
        hint: "부",
        season: 1,
      },
      {
        name: "부투핑",
        image: "/teenieping/catalog/season-1-10.png",
        hint: "부",
        season: 1,
      },
      {
        name: "깜빡핑",
        image: "/teenieping/catalog/season-1-11.png",
        hint: "깜",
        season: 1,
      },
      {
        name: "띠용핑",
        image: "/teenieping/catalog/season-1-12.png",
        hint: "띠",
        season: 1,
      },
      {
        name: "주르핑",
        image: "/teenieping/catalog/season-1-13.png",
        hint: "주",
        season: 1,
      },
      {
        name: "차나핑",
        image: "/teenieping/catalog/season-1-14.png",
        hint: "차",
        season: 1,
      },
      {
        name: "따라핑",
        image: "/teenieping/catalog/season-1-15.png",
        hint: "따",
        season: 1,
      },
      {
        name: "나르핑",
        image: "/teenieping/catalog/season-1-16.png",
        hint: "나",
        season: 1,
      },
      {
        name: "무셔핑",
        image: "/teenieping/catalog/season-1-17.png",
        hint: "무",
        season: 1,
      },
      {
        name: "투투핑",
        image: "/teenieping/catalog/season-1-18.png",
        hint: "투",
        season: 1,
      },
      {
        name: "차캐핑",
        image: "/teenieping/catalog/season-1-19.png",
        hint: "차",
        season: 1,
      },
      {
        name: "떠벌핑",
        image: "/teenieping/catalog/season-1-20.png",
        hint: "떠",
        season: 1,
      },
      {
        name: "다조핑",
        image: "/teenieping/catalog/season-1-21.png",
        hint: "다",
        season: 1,
      },
      {
        name: "화나핑",
        image: "/teenieping/catalog/season-1-22.png",
        hint: "화",
        season: 1,
      },
      {
        name: "시러핑",
        image: "/teenieping/catalog/season-1-23.png",
        hint: "시",
        season: 1,
      },
      {
        name: "바네핑",
        image: "/teenieping/catalog/season-1-24.png",
        hint: "바",
        season: 1,
      },
      {
        name: "덜덜핑",
        image: "/teenieping/catalog/season-1-25.png",
        hint: "덜",
        season: 1,
      },
      {
        name: "그림핑",
        image: "/teenieping/catalog/season-1-26.png",
        hint: "그",
        season: 1,
      },
      {
        name: "무거핑",
        image: "/teenieping/catalog/season-1-27.png",
        hint: "무",
        season: 1,
      },
      {
        name: "꺼꿀핑",
        image: "/teenieping/catalog/season-1-28.png",
        hint: "꺼",
        season: 1,
      },
      {
        name: "씽씽핑",
        image: "/teenieping/catalog/season-1-29.png",
        hint: "씽",
        season: 1,
      },
      {
        name: "베베핑",
        image: "/teenieping/catalog/season-1-30.png",
        hint: "베",
        season: 1,
      },
      {
        name: "코자핑",
        image: "/teenieping/catalog/season-1-31.png",
        hint: "코",
        season: 1,
      },
      {
        name: "딱풀핑",
        image: "/teenieping/catalog/season-1-32.png",
        hint: "딱",
        season: 1,
      },
      {
        name: "모야핑",
        image: "/teenieping/catalog/season-1-33.png",
        hint: "모",
        season: 1,
      },
      {
        name: "토이핑",
        image: "/teenieping/catalog/season-1-34.png",
        hint: "토",
        season: 1,
      },
      {
        name: "또까핑",
        image: "/teenieping/catalog/season-1-35.png",
        hint: "또",
        season: 1,
      },
      {
        name: "플라핑",
        image: "/teenieping/catalog/season-1-36.png",
        hint: "플",
        season: 1,
      },
      {
        name: "노라핑",
        image: "/teenieping/catalog/season-1-37.png",
        hint: "노",
        season: 1,
      },
      {
        name: "노리핑",
        image: "/teenieping/catalog/season-1-38.png",
        hint: "노",
        season: 1,
      },
      {
        name: "아휴핑",
        image: "/teenieping/catalog/season-1-39.png",
        hint: "아",
        season: 1,
      },
      {
        name: "똑똑핑",
        image: "/teenieping/catalog/season-1-40.png",
        hint: "똑",
        season: 1,
      },
      {
        name: "꽁꽁핑",
        image: "/teenieping/catalog/season-1-41.png",
        hint: "꽁",
        season: 1,
      },
      {
        name: "찌릿핑",
        image: "/teenieping/catalog/season-1-42.png",
        hint: "찌",
        season: 1,
      },
      {
        name: "홀로핑",
        image: "/teenieping/catalog/season-1-43.png",
        hint: "홀",
        season: 1,
      },
      {
        name: "악동핑",
        image: "/teenieping/catalog/season-1-44.png",
        hint: "악",
        season: 1,
      },
      {
        name: "앙대핑",
        image: "/teenieping/catalog/season-1-45.png",
        hint: "앙",
        season: 1,
      },
      {
        name: "다이아 하츄핑",
        image: "/teenieping/catalog/season-2-01.png",
        hint: "다",
        season: 2,
      },
      {
        name: "조아핑",
        image: "/teenieping/catalog/season-2-02.png",
        hint: "조",
        season: 2,
      },
      {
        name: "방글핑",
        image: "/teenieping/catalog/season-2-03.png",
        hint: "방",
        season: 2,
      },
      {
        name: "믿어핑",
        image: "/teenieping/catalog/season-2-04.png",
        hint: "믿",
        season: 2,
      },
      {
        name: "까르핑",
        image: "/teenieping/catalog/season-2-05.png",
        hint: "까",
        season: 2,
      },
      {
        name: "아야핑",
        image: "/teenieping/catalog/season-2-06.png",
        hint: "아",
        season: 2,
      },
      {
        name: "소원핑",
        image: "/teenieping/catalog/season-2-07.png",
        hint: "소",
        season: 2,
      },
      {
        name: "토닥핑",
        image: "/teenieping/catalog/season-2-08.png",
        hint: "토",
        season: 2,
      },
      {
        name: "쪼꼼핑",
        image: "/teenieping/catalog/season-2-09.png",
        hint: "쪼",
        season: 2,
      },
      {
        name: "싹싹핑",
        image: "/teenieping/catalog/season-2-10.png",
        hint: "싹",
        season: 2,
      },
      {
        name: "맛나핑",
        image: "/teenieping/catalog/season-2-11.png",
        hint: "맛",
        season: 2,
      },
      {
        name: "포근핑",
        image: "/teenieping/catalog/season-2-12.png",
        hint: "포",
        season: 2,
      },
      {
        name: "메모핑",
        image: "/teenieping/catalog/season-2-13.png",
        hint: "메",
        season: 2,
      },
      {
        name: "공쥬핑",
        image: "/teenieping/catalog/season-2-14.png",
        hint: "공",
        season: 2,
      },
      {
        name: "짝짝핑",
        image: "/teenieping/catalog/season-2-15.png",
        hint: "짝",
        season: 2,
      },
      {
        name: "주네핑",
        image: "/teenieping/catalog/season-2-16.png",
        hint: "주",
        season: 2,
      },
      {
        name: "뚝딱핑",
        image: "/teenieping/catalog/season-2-17.png",
        hint: "뚝",
        season: 2,
      },
      {
        name: "발레핑",
        image: "/teenieping/catalog/season-2-18.png",
        hint: "발",
        season: 2,
      },
      {
        name: "원더핑",
        image: "/teenieping/catalog/season-2-19.png",
        hint: "원",
        season: 2,
      },
      {
        name: "가면핑",
        image: "/teenieping/catalog/season-2-20.png",
        hint: "가",
        season: 2,
      },
      {
        name: "플로라 하츄핑",
        image: "/teenieping/catalog/season-3-01.png",
        hint: "플",
        season: 3,
      },
      {
        name: "꾸래핑",
        image: "/teenieping/catalog/season-3-02.png",
        hint: "꾸",
        season: 3,
      },
      {
        name: "나나핑",
        image: "/teenieping/catalog/season-3-03.png",
        hint: "나",
        season: 3,
      },
      {
        name: "솔찌핑",
        image: "/teenieping/catalog/season-3-04.png",
        hint: "솔",
        season: 3,
      },
      {
        name: "빨리핑",
        image: "/teenieping/catalog/season-3-05.png",
        hint: "빨",
        season: 3,
      },
      {
        name: "얌얌핑",
        image: "/teenieping/catalog/season-3-06.png",
        hint: "얌",
        season: 3,
      },
      {
        name: "뜨거핑",
        image: "/teenieping/catalog/season-3-07.png",
        hint: "뜨",
        season: 3,
      },
      {
        name: "삐뽀핑",
        image: "/teenieping/catalog/season-3-08.png",
        hint: "삐",
        season: 3,
      },
      {
        name: "힘내핑",
        image: "/teenieping/catalog/season-3-09.png",
        hint: "힘",
        season: 3,
      },
      {
        name: "고쳐핑",
        image: "/teenieping/catalog/season-3-10.png",
        hint: "고",
        season: 3,
      },
      {
        name: "아라핑",
        image: "/teenieping/catalog/season-3-11.png",
        hint: "아",
        season: 3,
      },
      {
        name: "패션핑",
        image: "/teenieping/catalog/season-3-12.png",
        hint: "패",
        season: 3,
      },
      {
        name: "꼼딱핑",
        image: "/teenieping/catalog/season-3-13.png",
        hint: "꼼",
        season: 3,
      },
      {
        name: "퐁당핑",
        image: "/teenieping/catalog/season-3-14.png",
        hint: "퐁",
        season: 3,
      },
      {
        name: "파티핑",
        image: "/teenieping/catalog/season-3-15.png",
        hint: "파",
        season: 3,
      },
      {
        name: "꾸며핑",
        image: "/teenieping/catalog/season-3-16.png",
        hint: "꾸",
        season: 3,
      },
      {
        name: "삐짐핑",
        image: "/teenieping/catalog/season-3-17.png",
        hint: "삐",
        season: 3,
      },
      {
        name: "아아핑",
        image: "/teenieping/catalog/season-3-18.png",
        hint: "아",
        season: 3,
      },
      {
        name: "빙글핑",
        image: "/teenieping/catalog/season-3-19.png",
        hint: "빙",
        season: 3,
      },
      {
        name: "행운핑",
        image: "/teenieping/catalog/season-3-20.png",
        hint: "행",
        season: 3,
      },
      {
        name: "다해핑",
        image: "/teenieping/catalog/season-3-21.png",
        hint: "다",
        season: 3,
      },
      {
        name: "베리 하츄핑",
        image: "/teenieping/catalog/season-4-01.png",
        hint: "베",
        season: 4,
      },
      {
        name: "샤샤핑",
        image: "/teenieping/catalog/season-4-02.png",
        hint: "샤",
        season: 4,
      },
      {
        name: "포실핑",
        image: "/teenieping/catalog/season-4-03.png",
        hint: "포",
        season: 4,
      },
      {
        name: "말랑핑",
        image: "/teenieping/catalog/season-4-04.png",
        hint: "말",
        season: 4,
      },
      {
        name: "캔디핑",
        image: "/teenieping/catalog/season-4-05.png",
        hint: "캔",
        season: 4,
      },
      {
        name: "머랭핑",
        image: "/teenieping/catalog/season-4-06.png",
        hint: "머",
        season: 4,
      },
      {
        name: "샌드핑",
        image: "/teenieping/catalog/season-4-07.png",
        hint: "샌",
        season: 4,
      },
      {
        name: "또너핑",
        image: "/teenieping/catalog/season-4-08.png",
        hint: "또",
        season: 4,
      },
      {
        name: "와플핑",
        image: "/teenieping/catalog/season-4-09.png",
        hint: "와",
        season: 4,
      },
      {
        name: "롤리핑",
        image: "/teenieping/catalog/season-4-10.png",
        hint: "롤",
        season: 4,
      },
      {
        name: "마카핑",
        image: "/teenieping/catalog/season-4-11.png",
        hint: "마",
        season: 4,
      },
      {
        name: "핫케핑",
        image: "/teenieping/catalog/season-4-12.png",
        hint: "핫",
        season: 4,
      },
      {
        name: "커핑&머핑",
        image: "/teenieping/catalog/season-4-13.png",
        hint: "커",
        season: 4,
      },
      {
        name: "요거핑",
        image: "/teenieping/catalog/season-4-14.png",
        hint: "요",
        season: 4,
      },
      {
        name: "눈꽃핑",
        image: "/teenieping/catalog/season-4-15.png",
        hint: "눈",
        season: 4,
      },
      {
        name: "푸딩핑",
        image: "/teenieping/catalog/season-4-16.png",
        hint: "푸",
        season: 4,
      },
      {
        name: "멜로핑",
        image: "/teenieping/catalog/season-4-17.png",
        hint: "멜",
        season: 4,
      },
      {
        name: "쪼꼬핑",
        image: "/teenieping/catalog/season-4-18.png",
        hint: "쪼",
        season: 4,
      },
      {
        name: "뿌뿌핑",
        image: "/teenieping/catalog/season-4-19.png",
        hint: "뿌",
        season: 4,
      },
      {
        name: "새콤핑",
        image: "/teenieping/catalog/season-4-20.png",
        hint: "새",
        season: 4,
      },
      {
        name: "달콤핑",
        image: "/teenieping/catalog/season-4-21.png",
        hint: "달",
        season: 4,
      },
      {
        name: "트러핑",
        image: "/teenieping/catalog/season-4-22.png",
        hint: "트",
        season: 4,
      },
      {
        name: "빤짝핑",
        image: "/teenieping/catalog/season-5-02.png",
        hint: "빤",
        season: 5,
      },
      {
        name: "빛나핑",
        image: "/teenieping/catalog/season-5-03.png",
        hint: "빛",
        season: 5,
      },
      {
        name: "초롱핑",
        image: "/teenieping/catalog/season-5-04.png",
        hint: "초",
        season: 5,
      },
      {
        name: "오로라핑",
        image: "/teenieping/catalog/season-5-05.png",
        hint: "오",
        season: 5,
      },
      {
        name: "나그네핑",
        image: "/teenieping/catalog/season-5-06.png",
        hint: "나",
        season: 5,
      },
      {
        name: "딩동핑",
        image: "/teenieping/catalog/season-5-07.png",
        hint: "딩",
        season: 5,
      },
      {
        name: "다롱핑",
        image: "/teenieping/catalog/season-5-08.png",
        hint: "다",
        season: 5,
      },
      {
        name: "아롱핑",
        image: "/teenieping/catalog/season-5-09.png",
        hint: "아",
        season: 5,
      },
      {
        name: "고마핑",
        image: "/teenieping/catalog/season-5-10.png",
        hint: "고",
        season: 5,
      },
      {
        name: "뽀송핑",
        image: "/teenieping/catalog/season-5-11.png",
        hint: "뽀",
        season: 5,
      },
      {
        name: "깡총핑",
        image: "/teenieping/catalog/season-5-12.png",
        hint: "깡",
        season: 5,
      },
      {
        name: "여우핑",
        image: "/teenieping/catalog/season-5-13.png",
        hint: "여",
        season: 5,
      },
      {
        name: "뿌쵸핑",
        image: "/teenieping/catalog/season-5-14.png",
        hint: "뿌",
        season: 5,
      },
      {
        name: "훌라핑",
        image: "/teenieping/catalog/season-5-15.png",
        hint: "훌",
        season: 5,
      },
      {
        name: "왕자핑",
        image: "/teenieping/catalog/season-5-16.png",
        hint: "왕",
        season: 5,
      },
      {
        name: "고고핑",
        image: "/teenieping/catalog/season-5-17.png",
        hint: "고",
        season: 5,
      },
      {
        name: "함께핑",
        image: "/teenieping/catalog/season-5-18.png",
        hint: "함",
        season: 5,
      },
      {
        name: "몰래핑",
        image: "/teenieping/catalog/season-5-19.png",
        hint: "몰",
        season: 5,
      },
      {
        name: "유리핑",
        image: "/teenieping/catalog/season-5-20.png",
        hint: "유",
        season: 5,
      },
      {
        name: "댄스핑",
        image: "/teenieping/catalog/season-5-21.png",
        hint: "댄",
        season: 5,
      },
      {
        name: "루루핑",
        image: "/teenieping/catalog/season-5-22.png",
        hint: "루",
        season: 5,
      },
      {
        name: "뽀뽀핑",
        image: "/teenieping/catalog/season-5-23.png",
        hint: "뽀",
        season: 5,
      },
      {
        name: "나눔핑",
        image: "/teenieping/catalog/season-5-24.png",
        hint: "나",
        season: 5,
      },
      {
        name: "로미핑",
        image: "/teenieping/catalog/season-5-25.png",
        hint: "로",
        season: 5,
      },
      {
        name: "프린세스 하츄핑",
        image: "/teenieping/catalog/season-6-01.png",
        hint: "프",
        season: 6,
      },
      {
        name: "사뿐핑",
        image: "/teenieping/catalog/season-6-02.png",
        hint: "사",
        season: 6,
      },
      {
        name: "아름핑",
        image: "/teenieping/catalog/season-6-03.png",
        hint: "아",
        season: 6,
      },
      {
        name: "뽀니핑",
        image: "/teenieping/catalog/season-6-04.png",
        hint: "뽀",
        season: 6,
      },
      {
        name: "다이아나핑",
        image: "/teenieping/catalog/season-6-05.png",
        hint: "다",
        season: 6,
      },
      {
        name: "이클립스핑",
        image: "/teenieping/catalog/season-6-06.png",
        hint: "이",
        season: 6,
      },
      {
        name: "뽀득핑",
        image: "/teenieping/catalog/season-6-07.png",
        hint: "뽀",
        season: 6,
      },
      {
        name: "차밍핑",
        image: "/teenieping/catalog/season-6-08.png",
        hint: "차",
        season: 6,
      },
      {
        name: "나비핑",
        image: "/teenieping/catalog/season-6-09.png",
        hint: "나",
        season: 6,
      },
      {
        name: "실크핑",
        image: "/teenieping/catalog/season-6-10.png",
        hint: "실",
        season: 6,
      },
      {
        name: "스노우핑",
        image: "/teenieping/catalog/season-6-11.png",
        hint: "스",
        season: 6,
      },
      {
        name: "이슬핑",
        image: "/teenieping/catalog/season-6-12.png",
        hint: "이",
        season: 6,
      },
      {
        name: "쿨쿨핑",
        image: "/teenieping/catalog/season-6-13.png",
        hint: "쿨",
        season: 6,
      },
      {
        name: "슈슈핑",
        image: "/teenieping/catalog/season-6-14.png",
        hint: "슈",
        season: 6,
      },
      {
        name: "롱롱핑",
        image: "/teenieping/catalog/season-6-15.png",
        hint: "롱",
        season: 6,
      },
      {
        name: "큐핑",
        image: "/teenieping/catalog/season-6-16.png",
        hint: "큐",
        season: 6,
      },
      {
        name: "야옹핑",
        image: "/teenieping/catalog/season-6-17.png",
        hint: "야",
        season: 6,
      },
      {
        name: "깨굴핑",
        image: "/teenieping/catalog/season-6-18.png",
        hint: "깨",
        season: 6,
      },
      {
        name: "트롯핑",
        image: "/teenieping/catalog/season-6-19.png",
        hint: "트",
        season: 6,
      },
      {
        name: "샤를핑",
        image: "/teenieping/catalog/season-6-20.png",
        hint: "샤",
        season: 6,
      },
      {
        name: "젠틀핑",
        image: "/teenieping/catalog/season-6-21.png",
        hint: "젠",
        season: 6,
      },
    ],
  },
  {
    slug: "wishcat",
    title: "위시캣",
    english: "WISH CAT",
    description: "19마리의 사랑스러운 위시캣 친구들",
    color: "#f06da9",
    softColor: "#fff0f8",
    accent: "#77d5e9",
    cover: "/wishcat/catalog/ainyang.png",
    characters: wishcatCharacters,
  },
  {
    slug: "mystery-apt",
    title: "신비아파트",
    english: "THE HAUNTED HOUSE",
    description: "54명의 오싹한 귀신과 등장인물",
    color: "#7654c4",
    softColor: "#f3efff",
    accent: "#b79cec",
    cover: "/mystery-apt/catalog/catalog-01.png",
    characters: mysteryAptCharacters,
  },
  {
    slug: "cinnamoroll",
    title: "시나모롤",
    english: "CINNAMOROLL",
    description: "시나모롤과 포근한 친구들 11명",
    color: "#65bde8",
    softColor: "#edf9ff",
    accent: "#8ed6f6",
    cover: "/cinnamoroll/catalog/cinnamoroll.png",
    characters: [
      {
        name: "시나모롤",
        image: "/cinnamoroll/catalog/cinnamoroll.png",
        hint: "시",
      },
      {
        name: "카푸치노",
        image: "/cinnamoroll/catalog/cappuccino.png",
        hint: "카",
      },
      { name: "모카", image: "/cinnamoroll/catalog/mocha.png", hint: "모" },
      { name: "쉬폰", image: "/cinnamoroll/catalog/chiffon.png", hint: "쉬" },
      {
        name: "에스프레소",
        image: "/cinnamoroll/catalog/espresso.png",
        hint: "에",
      },
      { name: "밀크", image: "/cinnamoroll/catalog/milk.png", hint: "밀" },
      {
        name: "작은새들",
        image: "/cinnamoroll/catalog/little-birds.png",
        hint: "작",
      },
      { name: "코코", image: "/cinnamoroll/catalog/coco.png", hint: "코" },
      { name: "넛츠", image: "/cinnamoroll/catalog/nuts.png", hint: "넛" },
      { name: "포롱", image: "/cinnamoroll/catalog/poron.png", hint: "포" },
      { name: "코르네", image: "/cinnamoroll/catalog/corune.png", hint: "코" },
    ],
  },
];

export const quizWorlds: QuizWorld[] = quizWorldData.map((world) =>
  world.slug !== "teenieping"
    ? world
    : {
        ...world,
        cover: world.cover.replace(/\.jpg$/, ".png"),
        characters: world.characters.map((character) => ({
          ...character,
          image: character.image.replace(/\.png$/, ".png"),
        })),
      },
);
export function getQuizWorld(slug: string) {
  return quizWorlds.find((world) => world.slug === slug);
}
